[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*"
  [headers.values]
    "Cache-Control" = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/src/*"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"
